### ISSUE TITLE
Perf: Improve by using ES Object to retrieve object values

### ISSUE THREAD

**Issue by MickaToast** [hustcc/tplv#1]
`const vs = Object.values(data);`
instead of
`const vs = ks.map((k: any) => data[k]);`
might improve performance.

<img width="1627" alt="Capture d’écran 2020-01-19 à 23 25 24" src="https://user-images.githubusercontent.com/9471827/72689646-e162fe00-3b13-11ea-881c-9f9a0a0f478e.png">

Above test was executed over non compiled code with 30 list and 16384 calls (https://aui.github.io/art-template/rendering-test/)

**Comment by hustcc** [comment]
Separate performance tests for two grammars: [jsperf](https://atool.vip/#/perf)

![image](https://user-images.githubusercontent.com/7856674/72692993-e5216f80-3b69-11ea-9977-a3946dea2c0a.png)

**Comment by hustcc** [comment]
@MickaToast I will add compile mode, for 13x performance up. #2 help to code review?

![image](https://user-images.githubusercontent.com/7856674/72694595-73005900-3b70-11ea-81dd-2bad6cc2a46a.png)
